[package]
name = "secure-store"
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/reggi/secure-store"
description = "ğŸ”ğŸª Securely save files in git repo in Keychain and write them back."

[dependencies]
clap = "4.5.1"
tokio = { version = "1", features = ["full"] }
path-clean = "1.0.1"
pathdiff = "0.2.1"
regex = "1.10.3"